seed: 42
device: "cuda:0"  # cpu or cuda

wandb:
  enabled: False
  project: "FF-TrueFace"
  group: "Face"

input:
  dataset: "TrueFace"
  path: /media/mmlab/Volume/truebees/TrueFace/
  pre_post: "pre"  # Select dataset: "pre" for PreSocial (1024x1024), "post" for PostSocial (FB: 720x720, TL, TW: 1024x1024)
  batch_size: 128
  image_size: 1024
  image_channels: 3
  num_classes: 2

transformer:
  dim: 256
  patch_size: 256
  heads: 12
  dim_head: 64

model:
  type: "ViT"

  peer_normalization: 0.03
  momentum: 0.9  # Momentum to use for the running mean in peer normalization loss.

  hidden_dim: 1000  # Classification layer dimension
  num_layers: 3


training:
  epochs: 200

  learning_rate: 1e-4
  weight_decay: 3e-4
  momentum: 0.9

  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3

  val_idx: 10  # -1: validate only once training has finished; n: validate every n epochs.
  final_test: True  # Set to true to evaluate performance on test-set.


hydra:
  run:
    dir: logs