seed: 42
device: "cuda"  # cpu or cuda

wandb:
  enabled: True
  project: "FF-TrueFace"
  group: "Face-ViT"

input:
  dataset: "TrueFace"
  path: /media/mmlab/Volume/truebees/TrueFace/  
  pre_post: "pre"  # "pre" or "post"
  batch_size: 128
  image_size: 1024
  image_channels: 3
  num_classes: 2

transformer:
  dim: 1024  # Transformer hidden layer dimension
  patch_size: 256
  heads: 16
  dim_head: 64

model:
  type: "ViT"

  peer_normalization: 0.03
  momentum: 0.9  # Momentum to use for the running mean in peer normalization loss.

  hidden_dim: 1024  # Classification layer dimension
  num_layers: 3


training:
  epochs: 200

  learning_rate: 1e-5
  weight_decay: 3e-4
  momentum: 0.9

  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3

  val_idx: 20  # -1: validate only once training has finished; n: validate every n epochs.
  final_test: True  # Set to true to evaluate performance on test-set.


hydra:
  run:
    dir: logs